export const projects = [
  {
    name: "Skill Up!",
    color: "#A21A42",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
  },
  {
    name: "On the Map",
    color: "#A21A42",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
  },
  {
    name: "Global Classroom",
    color: "#C51A2D",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
  },
  {
    name: "Finger Print",
    color: "#C51A2D",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
  },
  {
    name: "Scale Up",
    color: "#1A486A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
  },
  {
    name: "myself, my world",
    color: "#1A486A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
  },
  {
    name: "Green Leaders",
    color: "#3F7E45",
    bgColor: "#3F7E451A",
    hoverColor: "#3F7E4540",
  },
  {
    name: "Rooted",
    color: "#56C02A",
    bgColor: "#56C02A1A",
    hoverColor: "#56C02A40",
  },
];

export const opportunities = [
  {
    id: 1,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",

    project: "Skill Up!",
    opportunityLink: "LINK",
    provider: "école Errahma",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "26 Jan 2025",
    endDate: "9 Mar 2025",
    flexibility: "Fixed",
    exchangeFee: 116.0,
    accommodation: "Provided and Covered",
    food: "2 meals",
    otherBenefits: "transportation fees (12€/week)",
    required: "English speaker / Soft & Hard skills",
    preferred: "Facilitation skills",
  },
  {
    id: 2,
    bgColor: "#1A486A1A",
    modalBgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",

    project: "Scale Up",
    opportunityLink: "LINK",
    provider: "Eco village sousse",
    totalSlots: 2,
    slotsAvailable: 1,
    startDate: "1 Feb 2025",
    endDate: "15 Mar 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 3,
    modalBgColor: "#3F7E451A",
    bgColor: "#3F7E451A",
    hoverColor: "#3F7E4540",
    color: "#3F7E45",
    project: "Green Leaders",
    opportunityLink: "LINK",
    provider: "Eco village sousse",
    totalSlots: 5,
    slotsAvailable: 3,
    startDate: "1 Feb 2025",
    endDate: "15 Mar 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 4,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "On the Map",
    opportunityLink: "LINK",
    provider: "Eco village sousse",
    totalSlots: 5,
    slotsAvailable: 4,
    startDate: "1 Apr 2025",
    endDate: "15 May 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 5,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "LINK",
    provider: "Eco village sousse",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Apr 2025",
    endDate: "15 May 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 12,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "LINK",
    provider: "Select School Plus Skills",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "21 Jul 2025",
    endDate: "25 Aug 2025",
    flexibility: "Flexible",
    exchangeFee: 116.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "computer",
    required: "Arts Teacher",
    preferred: "",
  },
  {
    id: 6,
    modalBgColor: "#1A486A1A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",

    project: "Scale Up",
    opportunityLink: "LINK",
    provider: "Eco village sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "1 Jun 2025",
    endDate: "15 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 7,
    modalBgColor: "#1A486A1A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",

    project: "myself, my world",
    opportunityLink: "LINk",
    provider: "Eco village sousse",
    totalSlots: 5,
    slotsAvailable: 4,
    startDate: "1 Jun 2025",
    endDate: "15 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 8,
    modalBgColor: "#56C02A1A",
    bgColor: "#56C02A1A",
    hoverColor: "#56C02A40",
    color: "#56C02A",
    project: "Rooted",
    opportunityLink: "LINK",
    provider: "Eco village sousse",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Jun 2025",
    endDate: "15 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 9,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "On the Map",
    opportunityLink: "LINK",
    provider: "Big Holidays Tunisia",
    totalSlots: 20,
    slotsAvailable: 19,
    startDate: "7 Jul 2025",
    endDate: "18 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 300.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "transportation between cities is provided and covered",
    required: "",
    preferred: "Adaptability",
  },
  {
    id: 10,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "LINK",
    provider: "Association Arij",
    totalSlots: 2,
    slotsAvailable: 1,
    startDate: "1 Jul 2025",
    endDate: "12 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 86.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "English Teacher / French teacher",
    preferred: "",
  },
  {
    id: 11,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "LINK",
    provider: "Fleur De Vie",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "",
    endDate: "",
    flexibility: "Flexible",
    exchangeFee: 50.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Fluent French speaking and writing",
    preferred: "",
  },
];
