export const projects = [
  {
    name: "Skill Up!",
    color: "#A21A42",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
  },
  {
    name: "On the Map",
    color: "#A21A42",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
  },
  {
    name: "Global Classroom",
    color: "#C51A2D",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
  },
  {
    name: "Finger Print",
    color: "#C51A2D",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
  },
  {
    name: "Scale Up",
    color: "#1A486A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
  },
  {
    name: "myself, my world",
    color: "#1A486A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
  },
  {
    name: "Green Leaders",
    color: "#3F7E45",
    bgColor: "#3F7E451A",
    hoverColor: "#3F7E4540",
  },
  {
    name: "Rooted",
    color: "#56C02A",
    bgColor: "#56C02A1A",
    hoverColor: "#56C02A40",
  },
];

export const opportunities = [
  {
    id: 1,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "Skill Up!",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1314853",
    provider: "école Errahma",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "26 Jan 2025",
    endDate: "9 Mar 2025",
    flexibility: "Fixed",
    exchangeFee: 116.0,
    accommodation: "Provided and Covered",
    food: "2 meals",
    otherBenefits: "transportation fees (12€/week)",
    required: "English speaker / Soft & Hard skills",
    preferred: "Facilitation skills",
  },
  {
    id: 2,
    bgColor: "#1A486A1A",
    modalBgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",
    project: "Scale Up",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1316754",
    provider: "Eco village sousse",
    totalSlots: 2,
    slotsAvailable: 1,
    startDate: "1 Feb 2025",
    endDate: "15 Mar 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 3,
    modalBgColor: "#3F7E451A",
    bgColor: "#3F7E451A",
    hoverColor: "#3F7E4540",
    color: "#3F7E45",
    project: "Green Leaders",
    opportunityLink: "https://aiesec.org/opportunity/1316756",
    provider: "Eco village sousse",
    totalSlots: 5,
    slotsAvailable: 3,
    startDate: "1 Feb 2025",
    endDate: "15 Mar 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 4,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "On the Map",
    opportunityLink: "https://aiesec.org/opportunity/1316762",
    provider: "Eco village sousse",
    totalSlots: 5,
    slotsAvailable: 4,
    startDate: "1 Apr 2025",
    endDate: "15 May 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 5,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://aiesec.org/opportunity/1316763",
    provider: "Eco village sousse",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Apr 2025",
    endDate: "15 May 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 12,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://aiesec.org/opportunity/1307542",
    provider: "Select School Plus Skills",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "21 Jul 2025",
    endDate: "25 Aug 2025",
    flexibility: "Flexible",
    exchangeFee: 116.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "computer",
    required: "Arts Teacher",
    preferred: "",
  },
  {
    id: 6,
    modalBgColor: "#1A486A1A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",

    project: "Scale Up",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1316764",
    provider: "Eco village sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "1 Jun 2025",
    endDate: "15 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 7,
    modalBgColor: "#1A486A1A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",
    project: "myself, my world",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1316765",
    provider: "Eco village sousse",
    totalSlots: 5,
    slotsAvailable: 4,
    startDate: "1 Jun 2025",
    endDate: "15 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 8,
    modalBgColor: "#56C02A1A",
    bgColor: "#56C02A1A",
    hoverColor: "#56C02A40",
    color: "#56C02A",
    project: "Rooted",
    opportunityLink: "https://aiesec.org/opportunity/1316766",
    provider: "Eco village sousse",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Jun 2025",
    endDate: "15 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 9,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "On the Map",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1315418",
    provider: "Big Holidays Tunisia",
    totalSlots: 20,
    slotsAvailable: 19,
    startDate: "7 Jul 2025",
    endDate: "18 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 300.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "transportation between cities is provided and covered",
    required: "",
    preferred: "Adaptability",
  },
  {
    id: 10,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1315619",
    provider: "Association Arij",
    totalSlots: 2,
    slotsAvailable: 1,
    startDate: "1 Jul 2025",
    endDate: "12 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 86.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "English Teacher / French teacher",
    preferred: "",
  },
  {
    id: 11,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1307501",
    provider: "Fleur De Vie",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "",
    endDate: "",
    flexibility: "Flexible",
    exchangeFee: 50.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Fluent French speaking and writing",
    preferred: "",
  },
  {
    id: 13,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://expa.aiesec.org/opportunities/1320190/overview",
    provider: "so cute",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "6 Oct 2025",
    endDate: "15 Nov 2025",
    flexibility: "Fixed",
    exchangeFee: 95.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Instrumental player/Dancer/Theater Teacher",
    preferred: "",
  },
  {
    id: 14,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://expa.aiesec.org/opportunities/1320940/overview",
    provider: "Les Lauréats Private Middle School",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "1 Aug 2025",
    endDate: "25 Sep 2025",
    flexibility: "Fixed",
    exchangeFee: 100.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "transportation fees (7€/week)",
    required: "Theater Teacher",
    preferred: "",
  },
  {
    id: 15,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://expa.aiesec.org/opportunities/1320939/overview",
    provider: "Les Lauréats Private Middle School",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "1 Aug 2025",
    endDate: "12 Sep 2025",
    flexibility: "Fixed",
    exchangeFee: 100.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "transportation fees (7€/week)",
    required: "Arts Teacher",
    preferred: "",
  },
  {
    id: 16,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "https://expa.aiesec.org/opportunities/1320938/overview",
    provider: "Les Lauréats Private Middle School",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "1 Aug 2025",
    endDate: "25 Sep 2025",
    flexibility: "Fixed",
    exchangeFee: 100.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "transportation fees (7€/week)",
    required: "English Teacher",
    preferred: "",
  },
  {
    id: 17,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://aiesec.org/opportunity/1307542",
    provider: "Select School Plus Skills",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "21 Jul 2025",
    endDate: "25 Aug 2025",
    flexibility: "Flexible",
    exchangeFee: 116.0,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "computer",
    required: "Arts Teacher",
    preferred: "",
  },
  {
    id: 18,
    modalBgColor: "#3F7E451A",
    bgColor: "#3F7E451A",
    hoverColor: "#3F7E4540",
    color: "#3F7E45",
    project: "Green Leaders",
    opportunityLink: "https://aiesec.org/opportunity/1316756",
    provider: "Eco village sousse",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Aug 2025",
    endDate: "12 Sep 2025",
    flexibility: "Fixed",
    exchangeFee: 200.0,
    accommodation: "4 stars hotel",
    food: "1 meal",
    otherBenefits: "None",
    required: "",
    preferred: "",
  },
  {
    id: 19,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "Skill Up!",
    opportunityLink: "https://expa.aiesec.org/opportunities/1320920/overview",
    provider: "so cute",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "7 Jul 2025",
    endDate: "18 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 95.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Graphic designer",
    preferred: "",
  },
  {
    id: 20,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Finger Print",
    opportunityLink: "https://expa.aiesec.org/opportunities/1321151/overview",
    provider: "Ksiaa club d'arts",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 87.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Arts Teacher",
    preferred: "",
  },
  {
    id: 21,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Fingerprints",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1321912",
    provider: "Centre Culturel SEE",
    totalSlots: 4,
    slotsAvailable: 4,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 95.00,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Arts Teacher/Kids management",
    preferred: "",
  },
  { id: 24,
    modalBgColor: "#56C02A1A",
    bgColor: "#56C02A1A",
    hoverColor: "#56C02A40",
    color: "#56C02A",
    project: "Rooted",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322034",
    provider: "Association RPA sousse",
    totalSlots: 4,
    slotsAvailable: 4,
    startDate: "16 Jul 2025",
    endDate: "31 Aug 2025",
    flexibility: "Flexible",
    exchangeFee: 120.00,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Flexibility, motivation",
    preferred: "Veterinarian background"
  },
  {
    id: 25,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322665", 
    provider: "Scouts hamem sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "15 Jun 2025",
    endDate: "27 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Teaching languages(English) / kids management",
    preferred: "",
  },
  {
    id: 26,
    modalBgColor: "#1A486A1A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",
    project: "Scale Up",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322667", 
    provider: "Scouts hamem sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "15 Jun 2025",
    endDate: "27 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Marketing Background / social media management",
    preferred: "",
  },
  {
    id: 27,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Fingerprints",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322666", 
    provider: "Scouts hamem sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "15 Jun 2025",
    endDate: "27 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Arts Teacher/kids management",
    preferred: "",
  },
  {
    id: 28,
    modalBgColor: "#C51A2D1A", 
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Youth 4 Impact",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322670", 
    provider: "Scouts hamem sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "15 Jun 2025",
    endDate: "27 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Soft Skills / minimum knowledge about the environment and how to preserve it",
    preferred: "",
  },
  {
    id: 29,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "Skill Up!",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322673", 
    provider: "Scouts hamem sousse",
    totalSlots: 2,
    slotsAvailable: 2,
    startDate: "15 Jun 2025",
    endDate: "27 Jul 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "1 meal",
    otherBenefits: "None",
    required: "Skills in marketing / soft skills",
    preferred: "",
  },
  {
    id: 30,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Global Classroom",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322122",
    provider: "Youth Chart Mariem",
    totalSlots: 4,
    slotsAvailable: 4,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Teaching languages / kids management",
    preferred: "",
  },
  {
    id: 31,
    modalBgColor: "#1A486A1A",
    bgColor: "#1A486A1A",
    hoverColor: "#1A486A40",
    color: "#1A486A",
    project: "Scale Up",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322124",
    provider: "Youth Chart Mariem",
    totalSlots: 4,
    slotsAvailable: 4,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Marketing Background / social media management",
    preferred: "",
  },
  {
    id: 32,
    modalBgColor: "#c51a2e10",
    bgColor: "#C51A2D1A",
    hoverColor: "#C51A2D40",
    color: "#C51A2D",
    project: "Fingerprints",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322121",
    provider: "Youth Chart Mariem",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Arts teacher / Kids management",
    preferred: "",
  },
  {
    id: 33,
    modalBgColor: "#56C02A1A", // Using green color for Heartbeat based on the image
    bgColor: "#56C02A1A",
    hoverColor: "#56C02A40",
    color: "#56C02A",
    project: "Heartbeat",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322125",
    provider: "Youth Chart Mariem",
    totalSlots: 3,
    slotsAvailable: 3,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Fixed",
    exchangeFee: 110.00,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "First aid teaching / psychology",
    preferred: "",
  },
  {
    id: 1,
    modalBgColor: "#a21a430e",
    bgColor: "#A21A421A",
    hoverColor: "#A21A4240",
    color: "#A21A42",
    project: "Skill Up!",
    opportunityLink: "https://aiesec.org/opportunity/global-volunteer/1322123",
    provider: "Youth Chart Mariem",
    totalSlots: 1,
    slotsAvailable: 1,
    startDate: "1 Jul 2025",
    endDate: "14 Aug 2025",
    flexibility: "Flexible",
    exchangeFee: 110.0,
    accommodation: "Provided and Covered",
    food: "Not covered",
    otherBenefits: "None",
    required: "Entrepreneurship / Marketing  / Soft skills ",
    preferred: "",
  },
];
